### ISSUE TITLE
Sample code to send attachment image

### ISSUE THREAD

**Issue by kinkoi** [symphonyoss/symphony-java-client#11]
CC @maoo 
Hi @ftbb , is there any sample code for sending image attachment using the Symphony client? I'm building a bot that need this. Thanks,

https://github.com/kinkoi/eliza

Kinkoi

**Comment by ftbb** [comment]
Hi @kinkoi, 

Currently, the implementation of the file attachments API is not part of the java client.  

This will be a new feature I will attempt to add this week.

Note: we will be releasing the symphony-java-client this week under 0.9.0, so apologies for any inconvenience this has/will cause.

**Comment by maoo** [comment]
Thanks @ftbb ; adding few notes.

The 0.9.0 release of symphony-java-client will not affect the version 0.9.0-SNAPSHOT that is currently used by @kinkoi , since neither Maven Central nor Sonatype Snapshot (staging) repositories delete the deployed artifacts.

As soon as it's released, you can easily get notified about new releases using https://www.artifact-listener.org

**Comment by ftbb** [comment]
Please see commit 161596105b93035ea7902ae7cf90f072e249d87e
Example: https://github.com/symphonyoss/symphony-java-client/tree/master/symphony-client-examples/src/main/java/org/symphonyoss/examples/attachement

This is under 0.9.1 and requires 1.39+ Agent.
