### ISSUE TITLE
Create CI test BOT for functional integration testing

### ISSUE THREAD

**Issue by ftbb** [symphonyoss/symphony-java-client#42]
Test BOT to run independently to support all functional integration testing.

BOT responses will support echo of incoming messages or command based requests

- 1:1 Chat  
- Stream validation
- Multi-party Chat
- Multi-Party member confirmation
- Room Messaging
- Room member verification
- Basic presence validation

More to come...

**Comment by maoo** [comment]
Certificates created and Travis CI configured, see https://github.com/symphonyoss/symphony-java-client/pull/46

Please note that right now the cert download process haven't been tested yet, as it cannot run on Pull Requests, since they don't have access to environment variables (for [security reasons](https://docs.travis-ci.com/user/pull-requests))

**Comment by ftbb** [comment]
Travis CI integration and testing completed.  

commit 74f306edcc5126422b67fb3852d9a965c2b317a7

1:1 Chat and Room messaging functional.

**Comment by ftbb** [comment]
Initial base CI work completed.
