### ISSUE TITLE
Structure refactoring for symphony-java-api

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-client#43]
Following issue https://github.com/symphonyoss/symphony-java-client/issues/40 , I'd like to propose a new project structure that aims to:
- Define a clearer separation of concerns between
  - YAML files, managed by the Symphony team
  - Java APIs, generated code at build time
  - Symphony Java client, includes API additions/overrides (ie FireHose), interfaces and implementations
- Simplify the current structure, to make it easier to browse and understand and lower (to the strict necessary) the amount of released artifacts

# Current project structure
Right now, the Symphony API Swagger definition files are committed into 3 separate (Maven) sub-modules and generated as JAR files:
- symphony-apis/agent/api (symphony-agent-api)
- symphony-apis/authenticator/api (symphony-authenticator-api)
- symphony-apis/pod/api (symphony-pod-api)

JAR files are used by Jersey Client sub-modules, that add/override some APIs (see pom.xml files):
- symphony-agent-java-jersey2-client
- symphony-authenticator-java-jersey2-client
- symphony-pod-java-jersey2-client

Jersey Client sub-modules are used by `symphony-client`, which is shipped as the main library.

# Proposed structure
The code is split into 2 github repositories (they already exist):
1. **symphony-java-api**
  - includes a `./symphony-swagger-definitions` folder, which includes all YAML files delivered by Symphony; a first-level folder could define the API version (ie `v1.44.0`); optionally, this folder can be replaced by a git submodule that points to a different (public) git repository
  - defines a Maven build that
    - generates the Java source code and the JAR version, inheriting the deployment and release configurations of its parents
    - builds and publishes swagger html documentation into `gh-pages` branch
2. **symphony-java-client**
  - api-overrides - sub-module that re-packages symphony-java-api with the overrides currently implemented in the Jersey Client modules
  - symphony-client - sub-module that provides interface and implementation(s) of the Symphony Java Client; it depends only on the api-overrides module

**Comment by ftbb** [comment]
Work has started on this change.  

As part of this process, we are attempting to upgrade (from 1.40) to the latest REST API specification. 

It would seem the specification has been modified and a few key message types removed as of 1.45 (room related).

We are awaiting clarification before making further changes.

**Comment by jonfreedman** [comment]
I would also suggest a few refactoring tasks:
 - make all objects immutable (see [auto-value](https://github.com/google/auto/tree/master/value)) and then generate test coverage for them (see [evosuite](http://www.evosuite.org/))
 - remove unused [Joda](https://github.com/swagger-api/swagger-codegen/issues/2874) and also maybe Guava dependencies taken via Swagger
 - remove unused code / dependencies e.g. spring-boot, docker

I can create a branch for this work if you grant me commit privileges (otherwise I can fork...).  I have the changes ready to remove Joda and most of the unused code/pom references.

**Comment by jonfreedman** [comment]
I'm not sure about the value of publishing the swagger generated documentation to github pages, it seems to me that swagger-codegen is generating an entire project e.g. it contains `build.gradle`, `build.sbt`, `pom.xml` and `src\main\java` and `src\main\test` directories.  I think we have a simple decision to make, either generate symphony-java-api entirely via swagger-codegen or keep what we have currently where we throwing away everything other than the contents of `src\main\java`

**Comment by ftbb** [comment]
I have created a new branch "cleanup" to incorporate changes in SJC, removing symphony-java-apis module.  This has been tested with local repo, but we will need to publish snapshot of  new SJA (Symphony-java-api), which I think @maoo can help with into sonatype. 

I've updated the new symphony-java-api project to versioning consistent with published LLC Yaml to keep it consistent.

At this stage there is no need for an api-overrides module as this should be handled in the symphony-java-api project. (nice work @jonfreedman ) .  Also wondering how @jonfreedman was able to generate JSON inheritance tags under V2BaseMessage without overrides..again nice work.  

We are not publishing swagger documentation in the SJC.  SJC will publish standard javadoc for now under gh-pages.  SJA builds this automatically. 

I want to maintain a single module on SJC, because this could change in the future.

So next steps are to publish snapshot of SPA, merge cleanup branch into SJC master+develop.

**Comment by pmonks** [comment]
@jonfreedman I've had many instances where I've wished that the Javadocs for the swagger-generated code was Javadoc'ed somewhere.  For example [here](https://symphonyoss.github.io/symphony-java-client/org/symphonyoss/symphony/clients/StreamsClient.html) - it would be quite useful to know what that `org.symphonyoss.symphony.pod.model.Stream` object offers, given that it's "bled through" into the higher level client abstraction.

I realise that with the refactoring that's under way this object would be (at best) documented on a separate JavaDoc corpus (so there'd be no cross-linking between https://symphonyoss.github.io/symphony-java-cient/ and https://symphonyoss.github.io/symphony-java-api/), but at least it would be visible somewhere (which is still an improvement over the current situation).

FWIW in Clojure land it's easy enough for me to introspect those generated classes in a REPL at runtime, but that's not quite as easy to do in vanilla Java land (at least not until Java 9 lands).  It's also not as easy as just having Javadoc to refer to.

**Comment by ftbb** [comment]
We continue to separate things and provide better documentation through all avenues (gh-pages, README and Wiki).  

Distributions all have javadoc bundles included now.  This includes the symphony-java-api project and jersey2 distribution.  On the symphony-java-api jersey2 distribution the javadoc mirrors the documentation provided in the YAML spec.  

We should also see less bleeding in of models from the language bindings, because we continue to create abstractions.  For instance, in the latest 1.0.2 snapshot, SymStream has been introduced in replacement for Stream usages.  Methods using Stream have been deprecated.  

More to come here, just wanted to provide an update.

**Comment by ftbb** [comment]
We are moving into v1.1.0 which will be fairly clean based on removal of legacy code and new structure.  If there are any issues, please reopen.
