### ISSUE TITLE
Suggestion: URL logging for API calls

### ISSUE THREAD

**Issue by karlmoll** [symphonyoss/symphony-java-client#90]
I have not found a way to easily turn on logging of API calls (the URL that is formatted by the SDK, and the exact endpoint that is actually hit), and the exact response. Ideally you would be able to set various "verbose" logging as well, and set a log file to write out to.

**Comment by pmonks** [comment]
This may be related to issue #52, albeit that issue only requested endpoint information when an exception occurs, rather than allowing a developer to trace all endpoint calls (which is also handy!).

**Comment by ftbb** [comment]
This is a bit different, because you are looking for the actual REST API calls that are actually part of the symphony-java-api language binding and not SJC.  

SJC -->symphony-java-api-->REST API Endpoints

Here's some good news as the binding is Jersey2 and supports LoggingFeature, which is accessible from SJC!  With the following you will see all underlying calls.  If you really want to log it to a file, you can always create your own client with a logger to capture messages..or use logback and set by namespace.   

Try this:

      //Create an initialized client
            symClient = SymphonyClientFactory.getClient(
                    SymphonyClientFactory.TYPE.V4,symphonyClientConfig);

            symClient.getAgentHttpClient().property( 
            LoggingFeature.LOGGING_FEATURE_VERBOSITY_CLIENT,
            LoggingFeature.Verbosity.PAYLOAD_ANY);
            
            symClient.getAgentHttpClient().property( 
            LoggingFeature.LOGGING_FEATURE_LOGGER_LEVEL_CLIENT,   
           "WARNING");


Please close if you are happy with this response...
